#!/usr/bin/env bash
# powerdown - powerup
#

if [[ $EUID != 0 ]]; then
    echo "[powerdown] must be run as root"
    exit 1
fi

source PREFIX/lib/powerdown-functions
source ETCPREFIX/powerdown/conf

# diable nvidia cards
if [ "$BBSWITCH" == "on" ]; then
    if [ -f /proc/acpi/bbwitch ]; then
        echo ON > /proc/acpi/bbswitch
    fi
fi

# bus ... seems to be eeeeeevil
if [ "$BUS" == "true" ]; then
    for i in /sys/bus/*/devices/*/power/control; do
        opt "$i" on;
    done
fi

# usb autosuspend
if [ "$USB" == "true" ]; then
    if [ "$USB_autosuspend" == "true" ]; then
        for i in /sys/bus/usb/devices/*/power/autosuspend; do
            opt "$i" 600;
        done
    fi
    if [ "$USB_powersave" == "true" -a "$BUS" == "false" ]; then
        for i in /sys/bus/usb/devices/*/power/control; do opt "$i" on; done
    fi
fi

# nmi_watchdog
if [ "$NMI" == "true" ]; then
    opt /proc/sys/kernel/nmi_watchdog 1
fi

# cpu
if [ "$CPU" == "true" ]; then
    if [ ! -z "$CPU_powered_governor" ]; then
        case "$CPU_powered_governor" in
            powersave|ps|psafe) CPU_GOV="powersave" ;;
            ondemand|od) CPU_GOV="ondemand" ;;
            conservative|cv) CPU_GOV="conservative" ;;
            *) CPU_GOV= ;;
        esac
        for i in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do
            opt "$i" $CPU_GOV;
        done
    fi
    if [ "$CPU_powered_thermal" == "true" ]; then
        # FIXME bad scaling i think
        for i in /sys/class/thermal/cooling_device*; do
            opt "$i/cur_state" "$(num_scale "$i/max_state" 4)";
        done
    fi
fi

# aspm
if [ "$ASPM" == "true" ]; then
    opt /sys/module/pcie_aspm/parameters/policy default
fi

# kernel write mode
if [ "$VM" == "true" ]; then
    opt /proc/sys/vm/laptop_mode 0
    opt /proc/sys/vm/dirty_ratio 30
    opt /proc/sys/vm/dirty_background_ratio 10
    opt /proc/sys/vm/dirty_expire_centisecs 600
    opt /proc/sys/vm/dirty_writeback_centisecs 600
fi

# disk
if [ "$DISK" == "true" ]; then
    if [ "$DISK_link_pm" == "true" ]; then
        for i in /sys/class/scsi_host/host*/link_power_management_policy; do
            opt "$i" medium_power;
        done
    fi
    if [ "$DISK_mount_options" == "true" ]; then
        for dev in $(awk '/^\/dev\/sd.*ext[0-9]/ {print $1}' /etc/mtab); do
            run mount -o remount,relatime "$dev";
        done
        for dev in $(awk '/^\/dev\/sd/ {print $1}' /etc/mtab); do
            run blockdev --setra 256 "$dev";
        done
    fi
    if [ "$DISK_spindown" != "" ]; then
        for dev in $DISK_spindown; do
            run hdparm -B 254 -S 253 "$dev";
        done
    fi
fi

# sound card
if [ "$SOUND" == "true" ]; then
    opt /sys/module/snd_hda_intel/parameters/power_save 0
    opt /sys/module/snd_hda_intel/parameters/power_save_controller N
    opt /sys/module/snd_ac97_codec/parameters/power_save 0
fi

# net
if [ "$NET" == "true" ]; then
    for i in $(iw dev | awk '$1 == "Interface" { print $2 }'); do
        run iw dev "$i" set power_save off;
    done
fi

# screen
if [ "$BACKLIGHT" == "true" ] ; then
    for i in /sys/class/backlight/${BACKLIGHT_type}*; do 
        # FIXME bad scaling i think
        max_brightness=$(cat $i/max_brightness)
        opt "$i/brightness" "$(num_scale "$i/max_brightness" 5)";
    done
fi

#if [ "$" == "true" ]; then

# webcam
if [ "$WEBCAM" == "true" ]; then
    load_mod uvcvideo
    load_mod videodev
fi

# bluetooth
if [ "$BLUETOOTH" == "true" ]; then
    load_mod btusb
    load_mod bluetooth
fi

# video
if [ "$VIDEO" == "true" ]; then
    # open source ATI
    if [ "$VIDEO_ati_open" == "true" ]; then
        opt /sys/class/drm/card0/device/power_method profile
        opt /sys/class/drm/card0/device/power_profile default
    fi
    # i915
    if [ "$VIDEO_intel" == "true" ]; then
        opt /sys/module/i915/parameters/i915_enable_rc6 0
    fi
fi

# other
for i in $(find /etc/powerdown/up -type f); do run $i; done

exit 0
